name: screen_size_provider
description: A simple inhereted widget that provides screen size without context.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^3.1.1
